import path from 'node:path';import os from 'node:os';import {access,mkdtemp,readdir,rm} from 'node:fs/promises';import PgBoss from 'pg-boss';import {PrismaClient} from '@prisma/client';import {LocalStorage} from '@auth/storage';import {afterAll,beforeAll,describe,expect,it} from 'vitest';import {createPdfFixture,requireSafeTestUrl,waitFor} from '../../api/test/pdf-integration.fixture.js';import {PrismaPdfFinalizationRepository} from '../../api/src/pdf/pdf-finalization.repository.js';import {PdfFinalizationService} from '../../api/src/pdf/pdf-finalization.service.js';import {PdfFinalizationConsumer} from '../../api/src/pdf/pdf-finalization.consumer.js';import {startWorkerProcess,stopWorkerProcess} from './helpers/worker-process.js';
const url=requireSafeTestUrl();const suite=url?describe:describe.skip;
suite('PDF worker hard-crash recovery',()=>{
  let prisma:PrismaClient;let boss:PgBoss;let root:string;
  beforeAll(async()=>{root=await mkdtemp(path.join(os.tmpdir(),'auth-worker-recovery-'));prisma=new PrismaClient({datasources:{db:{url}}});boss=new PgBoss(url!);await boss.start();await boss.createQueue('authorization-pdf-finalized',{name:'authorization-pdf-finalized',policy:'singleton'});const service=new PdfFinalizationService(new PrismaPdfFinalizationRepository({db:prisma} as any),new LocalStorage(root));const consumer=new PdfFinalizationConsumer(service);await boss.work('authorization-pdf-finalized',{pollingIntervalSeconds:1},async jobs=>{for(const job of jobs)await consumer.consume({id:job.id,data:job.data as any,retryCount:(job as any).retryCount,retryLimit:(job as any).retryLimit});});});
  afterAll(async()=>{await boss.stop({graceful:true,timeout:10_000});await prisma.$disconnect();await rm(root,{recursive:true,force:true});});
  it('fences the killed worker, recovers within 60 seconds, and preserves one immutable physical result',async()=>{
    const fixture=await createPdfFixture(prisma,root,'QUEUED');const entry=path.resolve('dist/apps/worker/src/main.js');const baseEnv={DATABASE_URL:url!,STORAGE_LOCAL_ROOT:root,CHROMIUM_EXECUTABLE_PATH:process.env.CHROMIUM_EXECUTABLE_PATH??'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',NODE_ENV:'test'};const first=startWorkerProcess({cwd:path.resolve('.'),env:{...baseEnv,PDF_STAGING_JOURNAL_DELAY_MS:'60000'},entry});await waitFor(()=>prisma.pdfTask.findUniqueOrThrow({where:{id:fixture.ids.task}}),task=>task.status==='PROCESSING',10_000);const staging=path.join(root,'staging',fixture.ids.task,`v${fixture.event.businessVersion}.stage`);await waitFor(async()=>{try{await access(staging);return true;}catch{return false;}},ready=>ready,30_000);const active=await prisma.pdfTask.findUniqueOrThrow({where:{id:fixture.ids.task}});expect(active.pendingStorageKey).toBeNull();const identity={snapshot:active.dataSnapshotVersion,signature:active.signatureVersion,generation:active.claimGeneration,resource:fixture.ids.resourceVersion};first.kill('SIGKILL');await new Promise(resolve=>first.once('exit',resolve));const restartedAt=Date.now();const second=startWorkerProcess({cwd:path.resolve('.'),env:baseEnv,entry});
    try{await waitFor(()=>prisma.businessCase.findUniqueOrThrow({where:{id:fixture.ids.caseId}}),item=>item.status==='COMPLETED',60_000);expect(Date.now()-restartedAt).toBeLessThanOrEqual(60_000);const task=await prisma.pdfTask.findUniqueOrThrow({where:{id:fixture.ids.task}});expect(task.dataSnapshotVersion).toBe(identity.snapshot);expect(task.signatureVersion).toBe(identity.signature);expect(task.claimGeneration).toBeGreaterThan(identity.generation);expect(await prisma.signingRecord.count({where:{id:fixture.ids.signing,resourceFileVersionId:identity.resource}})).toBe(1);expect(await prisma.fileVersion.count({where:{caseId:fixture.ids.caseId,purpose:'FINAL_PDF'}})).toBe(1);expect((await readdir(path.join(root,'sha256'),{recursive:true})).filter(name=>String(name).endsWith('.pdf'))).toHaveLength(1);expect(await prisma.auditEvent.count({where:{targetId:fixture.ids.caseId,action:'PDF_FINALIZED'}})).toBe(1);}finally{await stopWorkerProcess(second);}
  },70_000);
});
