import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { demoCases, requirementCatalog } from '../../api/demoData';
import { PageHeader, StatusChip } from '../dashboard/DashboardPage';
const tabs = ['基本信息', '物料明细', '客户问卷', '资料文件', '授权书', '审核记录', '操作日志'] as const;
export interface CaseDetailClient { getCase(): Promise<{ title: string }>; }
export function CaseDetailPage({ client }: { client?: CaseDetailClient }) {
  const { id = '' } = useParams(); const item = demoCases.find(c => c.id === id) ?? demoCases[0]; const [remoteTitle, setRemoteTitle] = useState<string>(); const [tab, setTab] = useState<(typeof tabs)[number]>('基本信息'); const [toast, setToast] = useState(''); const [linkEnabled, setLinkEnabled] = useState(true);
  useEffect(() => { if (client) void client.getCase().then(result => setRemoteTitle(result.title)); }, [client]);
  const act = (message: string) => { setToast(message); setTimeout(() => setToast(''), 1800); };
  return <main className="page"><PageHeader eyebrow={`业务单 ${id || item.id}`} title={remoteTitle ?? item.customerName} description="品牌物料委托生产资料收集" actions={<><StatusChip status={item.status} /><button className="button secondary">••• 更多操作</button></>} />
    {toast && <div className="toast">✓ {toast}</div>}
    <div className="detail-layout"><div className="detail-main"><div className="tabs" role="tablist">{tabs.map(t => <button role="tab" aria-selected={tab === t} className={tab === t ? 'active' : ''} key={t} onClick={() => setTab(t)}>{t}</button>)}</div><section className="panel tab-panel">
      {tab === '基本信息' && <div className="detail-sections"><Info title="委托方信息" items={[['企业名称', item.customerName], ['统一社会信用代码', '91330106MA2B••••••'], ['联系人', '张女士'], ['联系电话', '138****6688']]} /><Info title="受托方信息" items={[['工厂 / 部门', item.factory], ['负责人', item.owner], ['创建时间', '2026-08-05 15:32'], ['报价单编号', 'BJ20260805018']]} /></div>}
      {tab === '物料明细' && <div className="table-wrap"><table><thead><tr><th>物料名称</th><th>规格</th><th>数量</th><th>材质</th><th>工艺</th></tr></thead><tbody><tr><td>乳白PVC不干胶</td><td>10×10cm</td><td>1000</td><td>8丝乳白PVC</td><td>四色印刷、覆膜、模切</td></tr><tr><td>产品合格标签</td><td>6×4cm</td><td>2000</td><td>铜版纸</td><td>专色印刷、模切</td></tr></tbody></table></div>}
      {tab === '客户问卷' && <Info title="已提交信息" items={[['品牌名称', '云岚生活'], ['授权生产类别', '产品包装与标签'], ['授权有效期', '2027-08-05'], ['数据版本', '第 2 版 · 2026-08-06 10:25']]} />}
      {tab === '资料文件' && <div className="file-list">{requirementCatalog.slice(0, 5).map((r, i) => <div key={r.key}><span className={`file-icon ${i === 4 ? 'sensitive' : ''}`}>{i === 4 ? '敏' : 'PDF'}</span><div><strong>{r.name}</strong><p>{i === 2 ? '商标注册证_第35类.pdf · 1.8 MB' : `${r.name}.pdf · ${(1.2 + i / 2).toFixed(1)} MB`}</p></div><StatusChip status={i === 3 ? 'NEEDS_SUPPLEMENT' : 'COMPLETED'} /><button className="button ghost">查看版本</button></div>)}</div>}
      {tab === '授权书' && <div className="pdf-preview"><div className="pdf-page"><h3>委托生产授权书</h3><p>兹授权 <u>{item.factory}</u> 按照我方确认的资料，生产以下品牌物料……</p><div className="pdf-table">乳白PVC不干胶　10×10cm　1000个</div><div className="seal-placeholder">甲方<br/>签章处</div></div><div><h3>授权书状态</h3><p><StatusChip status={item.status === 'COMPLETED' ? 'COMPLETED' : 'PENDING_FINAL_PDF'} /></p><button className="button primary" onClick={() => act('已创建预览任务')}>生成预览</button><button className="button secondary">下载当前版本</button><div className="notice warning">当前为普通电子签署，不等同于第三方可靠电子签名。</div></div></div>}
      {tab === '审核记录' && <Timeline items={[['客户提交资料', '2026-08-06 10:25', '张女士'], ['审核员领取任务', '2026-08-06 10:31', '李审核'], ['营业执照审核通过', '2026-08-06 10:38', '李审核']]} />}
      {tab === '操作日志' && <Timeline items={[['创建业务单', '2026-08-05 15:32', item.owner], ['生成客户访问链接', '2026-08-05 15:33', item.owner], ['客户首次访问', '2026-08-05 18:02', '客户链接访问']]} />}
    </section></div><aside className="flow-sidebar"><section className="panel"><h2>客户填写链接</h2><div className={`link-status ${linkEnabled ? '' : 'off'}`}><span />{linkEnabled ? '访问正常' : '已停用'}</div><code className="link-code">forms.example.com/f/8Vt7Jx2QpL…</code><p>有效期至 2026-08-13 15:32</p><button className="button primary full" onClick={() => { navigator.clipboard?.writeText('https://forms.example.com/f/8Vt7Jx2QpL'); act('客户链接已复制'); }}>复制客户链接</button><div className="button-row"><button className="button secondary" onClick={() => act('链接已续期 7 天')}>续期</button><button className="button secondary" onClick={() => setLinkEnabled(!linkEnabled)}>{linkEnabled ? '停用' : '重新生成'}</button></div></section><section className="panel"><h2>流程进度</h2><Timeline compact items={[['业务单创建', '08-05 15:32', '已完成'], ['客户填写提交', '08-06 10:25', '已完成'], ['资料审核', '处理中', '当前步骤'], ['生成最终文件', '等待中', '未开始']]} /></section><button className="button danger-outline full" onClick={() => act('关闭业务单需要填写原因')}>关闭业务单</button></aside></div>
  </main>;
}
function Info({ title, items }: { title: string; items: string[][] }) { return <div className="info-block"><h2>{title}</h2><dl>{items.map(([k, v]) => <div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></div>; }
function Timeline({ items, compact }: { items: string[][]; compact?: boolean }) { return <div className={`timeline ${compact ? 'compact' : ''}`}>{items.map(([title, time, actor], i) => <div key={title}><span className={i < 2 ? 'done' : ''} /><div><strong>{title}</strong><p>{time} · {actor}</p></div></div>)}</div>; }
