import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { EmptyState, PageHeader, PageLoading, StatusChip } from '../dashboard/DashboardPage';
export type CaseSummary = { id: string; title: string; status: string; customerName?: string; factory?: string; owner?: string; updatedAt?: string; materialCount?: number };
export interface CaseListClient { listCases(): Promise<CaseSummary[]>; }
export function CaseListPage({ client }: { client: CaseListClient }) {
  const [cases, setCases] = useState<CaseSummary[]>(); const [query, setQuery] = useState(''); const [status, setStatus] = useState(''); const [page, setPage] = useState(1);
  useEffect(() => { client.listCases().then(setCases); }, [client]);
  const filtered = useMemo(() => (cases ?? []).filter(c => (!query || `${c.id}${c.title}${c.factory}${c.owner}`.toLowerCase().includes(query.toLowerCase())) && (!status || c.status === status)), [cases, query, status]);
  return <main className="page"><PageHeader eyebrow="业务中心" title="业务单管理" description="创建、跟踪和管理客户委托生产资料" actions={<Link className="button primary" to="/cases/new">＋ 新建业务单</Link>} />
    <section className="panel filter-panel"><div className="filters"><label className="search-field"><span>搜索</span><input aria-label="搜索业务单" value={query} onChange={e => setQuery(e.target.value)} placeholder="业务单编号、客户、工厂或负责人" /></label><label><span>业务状态</span><select value={status} onChange={e => setStatus(e.target.value)}><option value="">全部状态</option><option value="DRAFT">草稿</option><option value="AWAITING_CUSTOMER">待客户填写</option><option value="CUSTOMER_FILLING">客户填写中</option><option value="PENDING_REVIEW">待审核</option><option value="NEEDS_SUPPLEMENT">需补件</option><option value="PENDING_RE_REVIEW">待复审</option><option value="PENDING_FINAL_PDF">待生成最终文件</option><option value="FINAL_PDF_FAILED">最终文件生成失败</option><option value="COMPLETED">已完成</option><option value="CLOSED">已关闭</option></select></label><label><span>更新时间</span><input type="date" /></label><button className="button secondary align-bottom" onClick={() => { setQuery(''); setStatus(''); }}>重置</button></div></section>
    <section className="panel no-pad">{!cases ? <PageLoading text="正在加载业务单…" /> : filtered.length ? <><div className="table-wrap"><table><thead><tr><th>业务单编号</th><th>委托方 / 物料</th><th>受托工厂</th><th>负责人</th><th>状态</th><th>更新时间</th><th>操作</th></tr></thead><tbody>{filtered.map(c => <tr key={c.id}><td><Link className="table-link" to={`/cases/${c.id}`}>{c.id}</Link></td><td><strong>{c.customerName ?? c.title}</strong><small className="block">{c.materialCount ?? 0} 项物料</small></td><td>{c.factory ?? '—'}</td><td>{c.owner ?? '—'}</td><td><StatusChip status={c.status} /></td><td>{c.updatedAt ?? '—'}</td><td><Link to={`/cases/${c.id}`}>查看详情</Link><button className="more-button" aria-label="更多操作">•••</button></td></tr>)}</tbody></table></div><div className="pagination"><span>共 {filtered.length} 条记录</span><div><button disabled={page === 1} onClick={() => setPage(p => p - 1)}>上一页</button><button className="page-current">{page}</button><button disabled={filtered.length < 6} onClick={() => setPage(p => p + 1)}>下一页</button></div></div></> : <EmptyState title="没有找到业务单" text="请调整筛选条件，或创建一个新业务单" />}</section>
  </main>;
}
