import { useState } from 'react';
export interface CaseCommandClient { createCase(input: { customerName: string; contactName: string; factoryDepartment: string; materials: Array<{ name: string; specification: string; quantity: number; material: string; craft: string }>; templateVersionId: string; requirements?: string[] }): Promise<{ id: string }>; }
type MaterialDraft = { name: string; specification: string; quantity: string; material: string; craft: string };
const blankMaterial = (): MaterialDraft => ({ name: '', specification: '', quantity: '1', material: '', craft: '' });
export function CaseCreatePage({ client }: { client?: CaseCommandClient }) {
  const [customerName, setCustomerName] = useState(''); const [contactName, setContactName] = useState(''); const [factoryDepartment, setFactoryDepartment] = useState('');
  const [templateVersionId, setTemplateVersionId] = useState('default-authorization'); const [requirements, setRequirements] = useState<string[]>(['authorization']); const [materials, setMaterials] = useState<MaterialDraft[]>([blankMaterial()]); const [created, setCreated] = useState<string>();
  const submit = async () => { if (!customerName.trim()) return; const result = await client?.createCase({ customerName, contactName: contactName || '未填写', factoryDepartment: factoryDepartment || '未指定', templateVersionId, requirements, materials: materials.map(m => ({ name: m.name || '待补充物料', specification: m.specification || '待补充', quantity: Number(m.quantity) || 1, material: m.material || '待补充', craft: m.craft || '待补充' })) }); if (result) setCreated(`Case ${result.id} created`); };
  const updateMaterial = (index: number, key: keyof MaterialDraft, value: string) => setMaterials(list => list.map((m, i) => i === index ? { ...m, [key]: value } : m));
  return <main><h1>Create case</h1><label>Customer<input aria-label="Customer" value={customerName} onChange={e => setCustomerName(e.target.value)} /></label><label>Contact<input aria-label="Contact" value={contactName} onChange={e => setContactName(e.target.value)} /></label><label>Factory department<input aria-label="Factory department" value={factoryDepartment} onChange={e => setFactoryDepartment(e.target.value)} /></label><label>Template<select aria-label="Template" value={templateVersionId} onChange={e => setTemplateVersionId(e.target.value)}><option value="default-authorization">Default authorization</option><option value="brand-authorization">Brand authorization</option></select></label><label>Requirements<select multiple aria-label="Requirements" value={requirements} onChange={e => setRequirements(Array.from(e.target.selectedOptions, o => o.value))}><option value="authorization">Authorization letter (required)</option><option value="business-license">Business license</option><option value="trademark">Trademark certificate</option><option value="brand-chain">Brand authorization chain</option><option value="legal-id">Legal representative ID</option></select></label><h2>Materials</h2>{materials.map((m, i) => <fieldset key={i}><legend>Material {i + 1}</legend>{(['name', 'specification', 'quantity', 'material', 'craft'] as const).map(key => <input key={key} aria-label={`Material ${i + 1} ${key}`} placeholder={key} value={m[key]} onChange={e => updateMaterial(i, key, e.target.value)} />)}</fieldset>)}<button type="button" onClick={() => setMaterials([...materials, blankMaterial()])}>Add material</button><button type="button" onClick={submit}>Create case</button>{created && <p>{created}</p>}</main>; }
