import { useState } from 'react';
import { PageHeader } from '../dashboard/DashboardPage';
const sections = ['上游鉴权', '文件存储', '客户链接', '文件生成', '签署与证据'];
export function SettingsPage() { const [section,setSection]=useState('上游鉴权'); const [saved,setSaved]=useState(false); const save=()=>{setSaved(true);setTimeout(()=>setSaved(false),1800)}; return <main className="page"><PageHeader eyebrow="系统管理" title="系统设置" description="配置鉴权、存储、链接和文件生成服务" actions={<button className="button primary" onClick={save}>{saved?'✓ 已保存':'保存设置'}</button>} /><div className="settings-layout"><aside className="panel settings-nav">{sections.map(s=><button className={section===s?'active':''} onClick={()=>setSection(s)} key={s}>{s}<span>›</span></button>)}</aside><section className="panel settings-panel">
      {section==='上游鉴权'&&<><SettingTitle title="上游鉴权" text="使用现有系统 Token 调用 getInfo 获取用户、角色和权限" /><div className="form-grid one"><label><span>上游服务地址</span><input defaultValue="http://192.168.22.208:8080" /></label><label><span>用户信息接口</span><input defaultValue="/getInfo" /></label><div className="two-fields"><label><span>请求超时</span><div className="input-suffix"><input type="number" defaultValue={3}/><span>秒</span></div></label><label><span>成功缓存时间</span><div className="input-suffix"><input type="number" defaultValue={60}/><span>秒</span></div></label></div><label><span>服务间密钥</span><div className="secret-field"><input type="password" value="••••••••••••••••" readOnly/><button>重新设置</button></div><small>密钥只可写入，保存后无法读取明文。</small></label><button className="button secondary test-button">测试连接</button></div></>}
      {section==='文件存储'&&<><SettingTitle title="文件存储" text="当前使用本地磁盘，目录可在后续直接挂载为 NAS" /><div className="storage-options"><label className="selected"><input type="radio" name="storage" defaultChecked/><span>▣</span><div><strong>本地磁盘</strong><p>当前启用，适用于服务器本地或已挂载目录</p></div></label><label><input type="radio" name="storage"/><span>▤</span><div><strong>NAS / 网络存储</strong><p>预留模式，后续配置挂载路径后启用</p></div><em>暂未启用</em></label></div><label><span>文件根目录</span><input defaultValue="D:\authorization-files" /></label><div className="two-fields"><label><span>单文件上限</span><div className="input-suffix"><input defaultValue="20"/><span>MB</span></div></label><label><span>单业务单总量</span><div className="input-suffix"><input defaultValue="200"/><span>MB</span></div></label></div><div className="notice warning">当前版本尚未接入恶意文件扫描。上传文件一律作为附件下载，不会在服务器执行。</div></>}
      {section==='客户链接'&&<><SettingTitle title="客户链接" text="配置 H5 访问域名与默认有效期"/><label><span>H5 访问主域名</span><input defaultValue="https://forms.example.com"/></label><div className="two-fields"><label><span>默认有效期</span><div className="input-suffix"><input defaultValue="7"/><span>天</span></div></label><label><span>最大有效期</span><div className="input-suffix"><input defaultValue="30"/><span>天</span></div></label></div><div className="switch-row"><span><strong>完成后自动关闭访问</strong><small>最终文件生成成功后，客户链接立即失效</small></span><input type="checkbox" defaultChecked/></div><div className="notice info">链接令牌随机、不可猜测且不少于 128 位熵；系统数据库仅保存令牌摘要。</div></>}
      {section==='文件生成'&&<><SettingTitle title="文件生成与工作进程" text="配置 PDF 预览、最终文件与失败重试"/><label><span>工作进程服务地址</span><input defaultValue="http://127.0.0.1:3001"/></label><div className="two-fields"><label><span>自动重试次数</span><input type="number" defaultValue={3}/></label><label><span>任务恢复间隔</span><div className="input-suffix"><input defaultValue="60"/><span>秒</span></div></label></div><label><span>PDF 字体包</span><select><option>思源宋体 + 思源黑体</option></select></label><label><span>页面规格</span><select><option>A4 纵向</option></select></label><button className="button secondary test-button">检查工作进程状态</button></>}
      {section==='签署与证据'&&<><SettingTitle title="签署与证据" text="第一版使用普通电子签署，并为后续证据增强保留接口"/><div className="sign-mode"><strong>当前签署模式</strong><span>普通电子签署</span><p>支持手写签名或上传印章图，二选一覆盖到授权书签章区域。</p></div><div className="notice warning"><strong>法律能力提示</strong><br/>当前模式不等同于第三方可靠电子签名，不提供实名认证、CA 证书或可信时间戳。</div><h3>证据留存</h3>{['签署前 PDF 与 SHA-256 摘要','签署时间、客户端地址与用户代理','签署方式与签章资源版本','数据变更后使原签署失效'].map(x=><label className="evidence" key={x}><input type="checkbox" defaultChecked disabled/>✓ {x}</label>)}<h3>后续增强接口</h3><div className="reserved-grid"><span>实名认证<em>预留</em></span><span>CA 证书<em>预留</em></span><span>可信时间戳<em>预留</em></span><span>证据报告<em>预留</em></span></div></>}
    </section></div></main>; }
function SettingTitle({title,text}:{title:string;text:string}){return <div className="setting-title"><h2>{title}</h2><p>{text}</p></div>}
