module.exports = {
  apps: [
    {
      name: 'authorization-api',
      cwd: __dirname,
      script: 'apps/api/dist/apps/api/src/main.js',
      instances: 1,
      exec_mode: 'fork',
      env: { NODE_ENV: 'production', PG_BOSS_ENABLED: 'true' },
      autorestart: true,
      kill_timeout: 30000,
      listen_timeout: 10000,
      max_restarts: 10,
      restart_delay: 3000,
      merge_logs: true,
      time: true,
    },
    {
      name: 'authorization-pdf-worker',
      cwd: __dirname,
      script: 'apps/worker/dist/apps/worker/src/main.js',
      instances: 1,
      exec_mode: 'fork',
      env: { NODE_ENV: 'production' },
      autorestart: true,
      kill_timeout: 30000,
      max_restarts: 10,
      restart_delay: 3000,
      exp_backoff_restart_delay: 100,
      merge_logs: true,
      time: true,
    },
  ],
};
