[CmdletBinding()]
param([Parameter(Mandatory)][string]$DatabaseUrl,[Parameter(Mandatory)][string]$FileRoot,[Parameter(Mandatory)][string]$BackupRoot,[string]$PgDumpExecutable='pg_dump',[switch]$Execute,[switch]$Approved)
$ErrorActionPreference='Stop';if($DatabaseUrl-notmatch'^postgres(ql)?://'){throw 'Only PostgreSQL URLs are supported'};$file=[IO.Path]::GetFullPath($FileRoot);$backup=[IO.Path]::GetFullPath($BackupRoot)
if($file-eq$backup-or$backup.StartsWith($file+[IO.Path]::DirectorySeparatorChar)){throw 'Backup root must not be inside file root'};if([IO.Path]::GetPathRoot($backup)-eq$backup){throw 'Backup root must not be a drive root'}
Write-Output "VALID FILE_ROOT=$file";Write-Output "VALID BACKUP_ROOT=$backup";Write-Output 'PLAN pg_dump custom format; incremental hard-link/copy; SHA-256 manifest'
if(-not $Execute){Write-Output 'DRY_RUN no database read and no file copy';exit 0};if(-not $Approved){throw 'Execute requires -Approved'};if(-not(Test-Path -LiteralPath $file -PathType Container)){throw 'FileRoot does not exist'}
$pg=(Get-Command $PgDumpExecutable -ErrorAction Stop).Source;New-Item -ItemType Directory -Force -Path $backup|Out-Null;$previous=Get-ChildItem -LiteralPath $backup -Directory|Sort-Object Name -Descending|Select-Object -First 1;$previousManifest=$null
if($previous-and(Test-Path -LiteralPath (Join-Path $previous.FullName 'sha256-manifest.json'))){$previousManifest=Get-Content -Raw -LiteralPath (Join-Path $previous.FullName 'sha256-manifest.json')|ConvertFrom-Json}
$stamp=(Get-Date -Format 'yyyyMMdd-HHmmss')+'-'+[guid]::NewGuid().ToString('N').Substring(0,6);$target=Join-Path $backup $stamp;$filesTarget=Join-Path $target 'files';New-Item -ItemType Directory -Force -Path $filesTarget|Out-Null
& $pg "--dbname=$DatabaseUrl" '--format=custom' "--file=$(Join-Path $target 'database.dump')";if($LASTEXITCODE-ne 0){throw 'pg_dump failed'}
$entries=@();foreach($source in Get-ChildItem -LiteralPath $file -File -Recurse){$relative=$source.FullName.Substring($file.Length).TrimStart('\');$destination=Join-Path $filesTarget $relative;New-Item -ItemType Directory -Force -Path (Split-Path $destination) | Out-Null;$hash=(Get-FileHash -LiteralPath $source.FullName -Algorithm SHA256).Hash.ToLowerInvariant();$old=$previousManifest.files|Where-Object{$_.path-eq$relative.Replace('\','/')}|Select-Object -First 1;$oldPath=if($previous){Join-Path $previous.FullName (Join-Path 'files' $relative)}else{''};if($old-and$old.sha256-eq$hash-and(Test-Path -LiteralPath $oldPath)){try{New-Item -ItemType HardLink -Path $destination -Target $oldPath|Out-Null}catch{Copy-Item -LiteralPath $oldPath -Destination $destination}}else{Copy-Item -LiteralPath $source.FullName -Destination $destination};$entries+=[pscustomobject]@{path=$relative.Replace('\','/');sha256=$hash;bytes=$source.Length}}
$dump=Get-Item -LiteralPath (Join-Path $target 'database.dump');$manifest=[ordered]@{version=1;createdAt=(Get-Date).ToString('o');parent=if($previous){$previous.Name}else{$null};database=[ordered]@{path='database.dump';sha256=(Get-FileHash -LiteralPath $dump.FullName -Algorithm SHA256).Hash.ToLowerInvariant();bytes=$dump.Length};files=$entries};$manifest|ConvertTo-Json -Depth 6|Set-Content -Encoding UTF8 -LiteralPath (Join-Path $target 'sha256-manifest.json');Write-Output "BACKUP_CREATED $target"
