import { useState } from 'react';
import { requirementCatalog } from '../../api/demoData';
import { PageHeader } from '../dashboard/DashboardPage';
export function RequirementsPage() { const [items, setItems] = useState(requirementCatalog); const [editing, setEditing] = useState<(typeof items)[number] | null>(null); const [history, setHistory] = useState(false); return <main className="page"><PageHeader eyebrow="配置中心" title="资料项配置" description="配置客户问卷字段、上传规则和发布版本" actions={<button className="button primary" onClick={() => setEditing({ key: '', name: '', type: '文本', required: false, status: '草稿', version: 'v1' })}>＋ 新建资料项</button>} /><div className="notice info">盖章授权书为每个业务单的系统必选资料，不能停用或取消必选。</div><section className="panel filter-panel"><div className="filters"><label className="search-field"><span>搜索资料项</span><input placeholder="中文名称或机器键" /></label><label><span>字段类型</span><select><option>全部类型</option><option>文本</option><option>长文本</option><option>单选</option><option>多选</option><option>日期</option><option>数字</option><option>文件</option><option>图片</option></select></label><label><span>发布状态</span><select><option>全部状态</option><option>草稿</option><option>已发布</option><option>已停用</option></select></label></div></section><section className="panel no-pad"><div className="table-wrap"><table><thead><tr><th>资料项</th><th>机器键</th><th>字段类型</th><th>必填规则</th><th>当前版本</th><th>状态</th><th>操作</th></tr></thead><tbody>{items.map(item => <tr key={item.key}><td><strong>{item.name}</strong>{item.required && <span className="mandatory">系统必选</span>}</td><td><code>{item.key}</code></td><td>{item.type}</td><td>{item.required ? '必填' : '按业务单选择'}</td><td>{item.version}</td><td><span className={`status-chip ${item.status === '草稿' ? 'status-draft' : 'status-completed'}`}>{item.status}</span></td><td><button className="link-button" onClick={() => setEditing(item)}>编辑</button><button className="link-button" onClick={() => setHistory(true)}>版本历史</button>{item.status === '草稿' && <button className="link-button" onClick={() => setItems(list => list.map(x => x.key === item.key ? { ...x, status: '已发布' } : x))}>发布</button>}</td></tr>)}</tbody></table></div></section>
    {editing && <Drawer title={editing.key ? `编辑资料项 · ${editing.name}` : '新建资料项'} close={() => setEditing(null)}><div className="form-grid one"><label><span>中文名称 <b>*</b></span><input defaultValue={editing.name} /></label><label><span>机器键 <b>*</b></span><input defaultValue={editing.key} disabled={editing.status === '已发布'} placeholder="例如 business_license" /><small>发布后机器键不可修改</small></label><label><span>字段类型</span><select defaultValue={editing.type}><option>文本</option><option>长文本</option><option>单选</option><option>多选</option><option>日期</option><option>数字</option><option>文件</option><option>图片</option></select></label><label><span>填写说明</span><textarea placeholder="向客户说明需要提交什么内容" /></label><label><span>示例</span><input placeholder="可选的填写示例" /></label><div className="switch-row"><span><strong>在选择此资料项时必填</strong><small>业务单选择后，客户必须填写或上传</small></span><input type="checkbox" defaultChecked /></div><div className="rule-box"><h3>文件规则</h3><label><span>允许类型</span><input value="PDF、PNG、JPEG" readOnly /></label><div className="two-fields"><label><span>单文件上限</span><input type="number" defaultValue={20} /></label><label><span>最多文件数</span><input type="number" defaultValue={10} /></label></div></div></div><div className="drawer-actions"><button className="button secondary" onClick={() => setEditing(null)}>取消</button><button className="button primary" onClick={() => setEditing(null)}>保存草稿</button></div></Drawer>}
    {history && <Drawer title="版本历史 · 盖章授权书" close={() => setHistory(false)}><div className="version-list"><div><strong>v3　当前版本</strong><Status text="已发布" /><p>2026-07-18 14:20 · 管理员</p><button>查看版本</button></div><div><strong>v2</strong><Status text="历史版本" /><p>2026-05-02 10:18 · 管理员</p><button>查看版本</button></div><div><strong>v1</strong><Status text="历史版本" /><p>2026-03-11 09:06 · 管理员</p><button>查看版本</button></div></div></Drawer>}
  </main>; }
export function Drawer({ title, close, children }: { title: string; close(): void; children: React.ReactNode }) { return <><button className="drawer-mask visible" aria-label="关闭" onClick={close} /><aside className="side-drawer"><header><h2>{title}</h2><button onClick={close}>×</button></header><div className="drawer-body">{children}</div></aside></>; }
function Status({ text }: { text: string }) { return <span className="status-chip status-completed">{text}</span>; }
