import { createHash } from 'node:crypto';
import { Injectable } from '@nestjs/common';
import { ActorType,CaseStatus,FinalizationDeliveryStatus,PdfTaskStatus,Prisma,type Prisma as PrismaTypes } from '@prisma/client';
import { PrismaService } from '../database/prisma.service';
import type { FinalizationInspection,PdfFinalizationRepository,PdfFinalizedEvent } from './pdf-finalization.service';
import { AuditWriter } from '../database/repositories/audit-writer';
const slots=(ast:any)=>{const values:any[]=[];const visit=(v:any)=>{if(Array.isArray(v))return v.forEach(visit);if(!v||typeof v!=='object')return;if(v.type==='signatureSlot'&&v.signer==='PARTY_A'&&v.required)values.push({slotId:v.slotId,page:v.page,x:v.x,y:v.y,width:v.width,height:v.height});Object.values(v).forEach(visit)};visit(ast);return values;};
const fingerprint=(value:unknown)=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
@Injectable()
export class PrismaPdfFinalizationRepository implements PdfFinalizationRepository{
  constructor(private readonly prisma:PrismaService){}
  inspect(event:PdfFinalizedEvent){return this.inspectDb(this.prisma.db,event);}
  reinspect(event:PdfFinalizedEvent,expectedFingerprint?:string){return this.prisma.db.$transaction(async tx=>{const inspection=await this.inspectDb(tx,event);if(expectedFingerprint&&inspection.dbFingerprint!==expectedFingerprint)throw new Error('PDF_FINALIZATION_DB_CHANGED');return inspection;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
  private async inspectDb(db:any,event:PdfFinalizedEvent):Promise<FinalizationInspection>{const task=await db.pdfTask.findFirst({where:{id:event.jobId,caseId:event.caseId,dataSnapshotVersion:event.businessVersion,status:PdfTaskStatus.SUCCEEDED,outputFileVersionId:event.fileObjectId},include:{businessCase:{include:{templateVersion:true,reviews:true}},signing:true,outputFileVersion:true}});if(!task||!task.outputFileVersion)throw new Error('PDF_FINALIZATION_TASK_NOT_FOUND');const payload=task.signing.payload as any;const required=slots(task.businessCase.templateVersion.ast);const positions=Array.isArray(payload?.positions)?payload.positions:[];const placementsValid=required.length>0&&required.every((slot:any)=>positions.some((p:any)=>p.slotId===slot.slotId&&p.page===slot.page&&Number.isFinite(p.x)&&Number.isFinite(p.y)&&Number.isFinite(p.width)&&Number.isFinite(p.height)&&p.width>0&&p.height>0&&p.x>=slot.x&&p.y>=slot.y&&p.x+p.width<=slot.x+slot.width&&p.y+p.height<=slot.y+slot.height))&&positions.length===required.length;const snapshot=await db.caseSnapshot.findUnique({where:{caseId_version:{caseId:event.caseId,version:event.businessVersion}},include:{requirements:true}});const approved=new Set(task.businessCase.reviews.filter((item:any)=>item.decision==='APPROVE').map((item:any)=>item.requirementVersionId));const dbFingerprint=fingerprint({task:[task.id,task.status,task.dataSnapshotVersion,task.signatureVersion,task.outputFileVersionId,task.outputSha256],caseStatus:task.businessCase.status,requirements:snapshot?.requirements.map((item:any)=>item.requirementVersionId).sort(),reviews:task.businessCase.reviews.map((item:any)=>[item.requirementVersionId,item.decision,item.version]).sort(),signing:[task.signing.id,task.signing.valid,task.signing.contentDigest,task.signing.draftVersion,payload?.declarationAccepted,positions],output:[task.outputFileVersion.id,task.outputFileVersion.sha256,task.outputFileVersion.contentDigest]});return{businessVersion:task.dataSnapshotVersion,materialsApproved:Boolean(snapshot)&&snapshot.requirements.every((item:any)=>approved.has(item.requirementVersionId)),declarationAccepted:payload?.declarationAccepted===true,signingValid:task.signing.valid&&task.signing.contentDigest===task.outputFileVersion.contentDigest,placementsValid,pdfReadable:false,pdfShaMatches:task.outputFileVersion.sha256===event.sha256&&task.outputSha256===event.sha256,storageKey:task.outputFileVersion.storageKey,persistedSha256:task.outputFileVersion.sha256,dbFingerprint};}
  finalize(event:PdfFinalizedEvent,expectedFingerprint?:string){return this.prisma.db.$transaction(async tx=>{const inspection=await this.inspectDb(tx,event);if(expectedFingerprint&&inspection.dbFingerprint!==expectedFingerprint)throw new Error('PDF_FINALIZATION_DB_CHANGED');if(!inspection.materialsApproved||!inspection.declarationAccepted||!inspection.signingValid||!inspection.placementsValid||!inspection.pdfShaMatches)throw new Error('PDF_FINALIZATION_PHASE2_GATE_FAILED');const item=await tx.businessCase.findUniqueOrThrow({where:{id:event.caseId}});const now=new Date();await tx.pdfTask.updateMany({where:{id:event.jobId,status:PdfTaskStatus.SUCCEEDED,outputFileVersionId:event.fileObjectId,outputSha256:event.sha256},data:{finalizationStatus:FinalizationDeliveryStatus.DELIVERED,finalizationFailure:null,finalizationFailedAt:null,finalizedAt:now}});if(item.status===CaseStatus.COMPLETED)return{kind:'duplicate' as const};if(item.status!==CaseStatus.FINALIZING&&item.status!==CaseStatus.PDF_FAILED)throw new Error('PDF_FINALIZATION_CASE_STATE_CHANGED');const moved=await tx.businessCase.updateMany({where:{id:event.caseId,status:item.status},data:{status:CaseStatus.COMPLETED}});if(moved.count!==1)throw new Error('PDF_FINALIZATION_CAS_FAILED');await tx.publicCaseLink.updateMany({where:{caseId:event.caseId,disabledAt:null,completedAt:null},data:{disabledAt:now,completedAt:now}});await tx.caseStatusHistory.create({data:{caseId:event.caseId,fromStatus:item.status,toStatus:CaseStatus.COMPLETED,actorUserId:'SYSTEM',reason:'最终 PDF 已验证'}});await AuditWriter.append(tx,{data:{actorType:ActorType.SYSTEM,action:'PDF_FINALIZED',targetType:'BusinessCase',targetId:event.caseId,detail:{jobId:event.jobId,businessVersion:event.businessVersion,fileObjectId:event.fileObjectId,sha256:event.sha256} as PrismaTypes.InputJsonValue}});return{kind:'completed' as const};},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
  recordDeliveryFailure(event:PdfFinalizedEvent,reason:string,terminal:boolean){return this.prisma.db.$transaction(async tx=>{const now=new Date();const changed=await tx.pdfTask.updateMany({where:{id:event.jobId,caseId:event.caseId,status:PdfTaskStatus.SUCCEEDED,outputFileVersionId:event.fileObjectId,outputSha256:event.sha256,finalizationStatus:{not:FinalizationDeliveryStatus.DELIVERED}},data:{finalizationAttempts:{increment:1},finalizationStatus:terminal?FinalizationDeliveryStatus.FAILED:FinalizationDeliveryStatus.PENDING,finalizationFailure:terminal?reason:null,finalizationFailedAt:terminal?now:null}});if(changed.count!==1)return;if(terminal){const moved=await tx.businessCase.updateMany({where:{id:event.caseId,status:CaseStatus.FINALIZING},data:{status:CaseStatus.PDF_FAILED}});if(moved.count===1)await tx.caseStatusHistory.create({data:{caseId:event.caseId,fromStatus:CaseStatus.FINALIZING,toStatus:CaseStatus.PDF_FAILED,actorUserId:'SYSTEM',reason:`PDF最终确认投递失败：${reason}`}});await AuditWriter.append(tx,{data:{actorType:ActorType.SYSTEM,action:'PDF_FINALIZATION_DELIVERY_FAILED',targetType:'BusinessCase',targetId:event.caseId,detail:{jobId:event.jobId,reason,terminal:true} as PrismaTypes.InputJsonValue}});}});}
}
