import {randomUUID} from 'node:crypto';
import {ActorType,FilePurpose,PdfTaskStatus,PrismaClient} from '@prisma/client';
import {MAX_CASE_BYTES} from '@auth/storage';
import {PrismaPdfJobRepository} from '../../worker/src/pdf/pdf-job.repository';
import {createPdfFixture,requireSafeTestUrl} from './pdf-integration.fixture';

const url=requireSafeTestUrl();const suite=url?describe:describe.skip;
suite('concurrent final PDF retained evidence capacity',()=>{let prisma:PrismaClient;beforeAll(()=>{prisma=new PrismaClient({datasources:{db:{url}}});});afterAll(()=>prisma.$disconnect());
  it('serializes completions on the case and permits only the result within 200MB',async()=>{const fixture=await createPdfFixture(prisma,process.env.STORAGE_LOCAL_ROOT??'data/private-files');const base=await prisma.pdfTask.findUniqueOrThrow({where:{id:fixture.ids.task}});const retained=await prisma.fileVersion.aggregate({where:{caseId:fixture.ids.caseId,OR:[{file:{removedAt:null}},{preSignPdfs:{some:{}}},{signingResources:{some:{}}},{derivedFileVersions:{some:{signingResources:{some:{}}}}},{purpose:FilePurpose.FINAL_PDF}]},_sum:{sizeBytes:true}});const padding=MAX_CASE_BYTES-1-(retained._sum.sizeBytes??0);expect(padding).toBeGreaterThan(0);const padRecord=await prisma.fileRecord.create({data:{caseId:fixture.ids.caseId}});await prisma.fileVersion.create({data:{fileId:padRecord.id,caseId:fixture.ids.caseId,version:1,originalName:'capacity.pdf',mimeType:'application/pdf',sizeBytes:padding,sha256:'c'.repeat(64),storageKey:`capacity/${randomUUID()}.pdf`,actorType:ActorType.SYSTEM,purpose:FilePurpose.MATERIAL}});const make=async(index:number)=>prisma.pdfTask.create({data:{caseId:base.caseId,templateVersionId:base.templateVersionId,dataSnapshotVersion:base.dataSnapshotVersion,signatureVersion:base.signatureVersion,idempotencyKey:`capacity:${randomUUID()}`,status:PdfTaskStatus.PROCESSING,attempts:1,maxAttempts:3,leaseToken:`lease-${index}`,claimGeneration:1,pendingStorageKey:`staging/cap-${index}/v${base.dataSnapshotVersion}.stage`,pendingSha256:String(index).repeat(64),pendingSizeBytes:1}});const [a,b]=await Promise.all([make(1),make(2)]);const repository=new PrismaPdfJobRepository(prisma);const finish=(task:typeof a,index:number)=>repository.complete({taskId:task.id,leaseToken:`lease-${index}`,claimGeneration:1,caseId:task.caseId,businessVersion:task.dataSnapshotVersion,storageKey:`sha256/${index}/${String(index).repeat(64)}.pdf`,relativePath:`sha256/${index}/${String(index).repeat(64)}.pdf`,sizeBytes:1,sha256:String(index).repeat(64),generatedAt:new Date()});const results=await Promise.allSettled([finish(a,1),finish(b,2)]);expect(results.filter(result=>result.status==='fulfilled')).toHaveLength(1);const rejected=results.find(result=>result.status==='rejected') as PromiseRejectedResult;expect(String(rejected.reason)).toContain('CASE_FILE_CAPACITY_EXCEEDED');expect(await prisma.fileVersion.count({where:{caseId:fixture.ids.caseId,purpose:FilePurpose.FINAL_PDF}})).toBe(2);});
});
