import {createHash} from 'node:crypto';import path from 'node:path';import {mkdir,mkdtemp,rm,writeFile} from 'node:fs/promises';import {spawn as nodeSpawn,execFileSync} from 'node:child_process';import sharp from 'sharp';import {describe,expect,it} from 'vitest';import {ChromiumPdfRenderer,PuppeteerPdfEngine} from '@auth/template-engine';import {validateReadablePdf} from '@auth/storage';import {PdfRenderer} from './pdf.renderer.js';
const executable=process.env.CHROMIUM_EXECUTABLE_PATH;
const wrapper=execFileSync('where.exe',['pdftoppm']).toString().split(/\r?\n/)[0];const popplerBin=path.resolve(path.dirname(wrapper),'../../native/poppler/Library/bin');const popplerExe=path.join(popplerBin,'pdftoppm.exe');const spawn=((command:string,args:string[],options:any)=>nodeSpawn(command==='pdftoppm'?popplerExe:command,args,{...options,shell:false})) as typeof nodeSpawn;
expect.extend({toBeFinite(received:number){return{pass:Number.isFinite(received),message:()=>`expected ${received} to be finite`};}});
declare module 'vitest'{interface Assertion<T=any>{toBeFinite():void}}
describe.skipIf(!executable)('real Chromium final renderer',()=>{
  it('renders a readable A4 PDF through the shared Task10 engine',async()=>{const resource=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl2nJ8AAAAASUVORK5CYII=','base64');const renderer=new PdfRenderer(new ChromiumPdfRenderer(new PuppeteerPdfEngine({executablePath:executable,timeoutMs:30_000})));const pdf=await renderer.renderFinal({renderInput:{templateVersionId:'chrome-smoke-v1',ast:{type:'page',children:[{type:'heading',level:1,children:[{type:'text',text:'委托生产物料授权书'}]},{type:'signatureSlot',slotId:'party-a',signer:'PARTY_A',page:1,x:10,y:40,width:160,height:80,required:true}]},snapshot:{},draftVersion:1,contentDigest:'a'.repeat(64)},resource:{bytes:resource,mimeType:'image/png',sha256:createHash('sha256').update(resource).digest('hex')},placements:[{slotId:'party-a',page:1,x:20,y:50,width:100,height:50}]});expect(pdf.subarray(0,5).toString()).toBe('%PDF-');expect((await validateReadablePdf(pdf)).pageCount).toBe(1);},60_000);
  it('places red signature overlays on their requested physical PDF pages',async()=>{const base=path.resolve('tmp/pdfs');await mkdir(base,{recursive:true});const temp=await mkdtemp(path.join(base,'two-page-'));try{const resource=await sharp({create:{width:20,height:20,channels:4,background:{r:255,g:0,b:0,alpha:1}}}).png().toBuffer();const renderer=new PdfRenderer(new ChromiumPdfRenderer(new PuppeteerPdfEngine({executablePath:executable,timeoutMs:30_000})));const pdf=await renderer.renderFinal({renderInput:{templateVersionId:'two-page',ast:{type:'page',children:[{type:'paragraph',children:[{type:'text',text:'第一页'}]},{type:'signatureSlot',slotId:'p1',signer:'PARTY_A',page:1,x:0,y:0,width:250,height:150,required:true},{type:'pageBreak'},{type:'paragraph',children:[{type:'text',text:'第二页'}]},{type:'signatureSlot',slotId:'p2',signer:'PARTY_A',page:2,x:0,y:0,width:300,height:150,required:true}]},snapshot:{},draftVersion:1,contentDigest:'e'.repeat(64)},resource:{bytes:resource,mimeType:'image/png',sha256:createHash('sha256').update(resource).digest('hex')},placements:[{slotId:'p1',page:1,x:20,y:30,width:40,height:40},{slotId:'p2',page:2,x:180,y:60,width:40,height:40}]});expect((await validateReadablePdf(pdf,{minimumPages:2})).pageCount).toBe(2);const pdfPath=path.join(temp,'two-pages.pdf');const prefix=path.join(temp,'page');await writeFile(pdfPath,pdf);await new Promise<void>((resolve,reject)=>{const child=spawn('pdftoppm',['-png',pdfPath,prefix],{shell:true,stdio:'ignore'});child.once('exit',code=>code===0?resolve():reject(new Error(`pdftoppm exited ${code}`)));child.once('error',reject);});const minRedX=async(file:string)=>{const {data,info}=await sharp(file).removeAlpha().raw().toBuffer({resolveWithObject:true});let min=Infinity;for(let y=0;y<info.height;y++)for(let x=0;x<info.width;x++){const i=(y*info.width+x)*3;if(data[i]>180&&data[i+1]<100&&data[i+2]<100)min=Math.min(min,x);}return min;};const first=await minRedX(`${prefix}-1.png`);const second=await minRedX(`${prefix}-2.png`);expect(first).toBeFinite();expect(second).toBeFinite();expect(first).toBeLessThan(second);}finally{await rm(temp,{recursive:true,force:true});}},60_000);
});
